/**
 * Generates `example/theme.css` from the {@link kittTheme} schema using
 * @marianmeres/design-tokens. This is the "design-tokens approach": author a
 * typed `ThemeSchema`, generate the `--app-color-*` custom properties (light +
 * dark, with auto-derived hover/active states), and style the page against
 * those semantic variables.
 *
 * Run with:  deno task example:theme
 */
import { generateThemeCss } from "@marianmeres/design-tokens";
import { kittTheme } from "./src/theme.ts";

const banner = "/* GENERATED by example/gen-theme.ts — do not edit by hand.\n" +
	"   Source: example/src/theme.ts · Regenerate: deno task example:theme */\n\n";

const css = generateThemeCss(kittTheme, "app-");
const out = new URL("./theme.css", import.meta.url);

await Deno.writeTextFile(out, banner + css + "\n");
console.log(`wrote ${out.pathname}`);
